### ISSUE TITLE
[Feature request] 大佬NB，有沒有考慮開源下?

### ISSUE THREAD

**Issue by HuJK** [gdtool/cloudflare-workers-blog#1]
RT, 大佬NB，有沒有考慮開源下?

我相信大佬一定花了很多時間搞這個。

我只是問問，大老有考慮開源嗎?
沒有要壓迫的意思，如果大佬有自己的考慮，不打算開源，也能理解。

**Comment by gdtool** [comment]
观察观察再说,人多就开源
