### ISSUE TITLE
希望切换字体源

### ISSUE THREAD

**Issue by Seele-Vollerei32** [gdtool/cloudflare-workers-blog#13]
可以看到googlefonts国内加载太慢了，甚至比著名的cloudflare“减速器”还慢
![image](https://user-images.githubusercontent.com/83913312/134444822-5643c3d8-0ba9-4fdc-9abe-5d279ee992a2.png)

**Comment by dotfrankruan** [comment]
你可以自己fork一份前端然后自己下完放在里面啊
