### ISSUE TITLE
大佬，请问 如何让 markdown 支持 mathjax(TeX) 啊？

### ISSUE THREAD

**Issue by yanyuechuixue** [gdtool/cloudflare-workers-blog#2]
我试了一下暂时不支持。

**Comment by gdtool** [comment]
参考这个 `tex  : true`
[editor.md + Tex 科学公式(katex)](http://editor.md.ipandao.com/examples/katex.html)

**Comment by gdtool** [comment]
已经支持,强制刷新

**Comment by yanyuechuixue** [comment]
请问 tex:true 是加在哪里？

**Comment by yanyuechuixue** [comment]
> 参考这个 `tex : true`
> [editor.md + Tex 科学公式(katex)](http://editor.md.ipandao.com/examples/katex.html)

请问 tex:true 是加在哪里？

**Comment by gdtool** [comment]
> 我试了一下暂时不支持。

回头我试一下只是把开关打开了

**Comment by yanyuechuixue** [comment]
已经支持了，谢谢。
