### ISSUE TITLE
[Bug|同类产品的疑惑]Markdown编辑器手机端问题

### ISSUE THREAD

**Issue by ChenYFan** [gdtool/cloudflare-workers-blog#8]
Hi @gdtool ，您的CF-worker-Blog的编辑器在手机端无法输入中文，是不是编辑器的问题？
手机型号：IPhone6s IOS12，Safari，原生输入法
我最近正在开发一套[基于Workers的Hexo后端](https://github.com/HexoPlusPlus/HexoPlusPlus)，但是我遇到了一个移动端编辑问题，我在Github上面寻找解决方法时看到了您的项目，做的不错，点赞！可惜编辑器问题得到解决就好了。

**Comment by gdtool** [comment]
我这里正常呢，除了字小点儿，可以加我tg探讨@haopian
